name: "Pull request pre-checks"
on:
  pull_request:
    branches: ["main"]
    paths: ["Kubernetes_terraform/**"]

jobs:
  pre-checks:
    name: 'pre-check'
    runs-on: ubuntu-latest
    environment: KubernetesTerraform
    if: github.ref == 'refs/heads/release'
    defaults:
      run:
        working-directory: ./Kubernetes_terraform
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0